# Generated by Django 4.2.2 on 2023-06-16 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=200)),
                ('Address', models.CharField(blank=True, max_length=200)),
                ('Gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('State', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('DistrictName', models.CharField(blank=True, max_length=100, null=True, verbose_name='DistrictName')),
                ('Course', models.CharField(max_length=100, null=True, verbose_name='Course')),
                ('Mobile', models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('Trainer', models.CharField(choices=[('Anagha', 'Anagha'), ('Gopika', 'Gopika'), ('Neethu', 'Neethu')], max_length=6, null=True)),
                ('StartDate', models.DateField(null=True)),
                ('EndDate', models.DateField(null=True)),
                ('City', models.CharField(max_length=50, null=True, verbose_name='City')),
                ('Batch', models.CharField(max_length=200, null=True)),
                ('DOB', models.DateField(null=True, verbose_name='Date of Birth')),
                ('PIN', models.PositiveIntegerField(blank=True, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Registered', models.BooleanField(default=False)),
                ('Fees', models.CharField(max_length=100, null=True, verbose_name='Fees')),
            ],
        ),
        migrations.CreateModel(
            name='FeesReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('receipt_number', models.CharField(max_length=50)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collected_to_account', models.CharField(choices=[('oneteam ac 1', 'Oneteam ac 1'), ('oneteam ac 2', 'Oneteam ac 2'), ('oneteam ac 3', 'Oneteam ac 3')], max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], max_length=50)),
                ('description', models.TextField(null=True)),
                ('receipt_image', models.ImageField(null=True, upload_to='receipts/')),
                ('Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
        migrations.CreateModel(
            name='FeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('one_times', 'One Time'), ('two_times', 'Two Times'), ('three_times', 'Three Times')], max_length=20, null=True)),
                ('first_pay', models.DateField(blank=True, null=True)),
                ('first_pay_amount', models.IntegerField(blank=True, null=True)),
                ('second_pay', models.DateField(blank=True, null=True)),
                ('second_pay_amount', models.IntegerField(blank=True, null=True)),
                ('third_pay', models.DateField(blank=True, null=True)),
                ('third_pay_amount', models.IntegerField(blank=True, null=True)),
                ('Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.students')),
            ],
        ),
    ]
